### ISSUE TITLE
Bug witch Battery icon on charging

### ISSUE THREAD

**Issue by DonTMover** [AniLabX/AniLabX#23]
Добрый вечер, заметил неприятный баг с функцией встроенного плеера, он показывает заряд, но на новом девайсе перестал 
Device: Asus Zenfone 10
App version: 3.12.49

~~Видео приложу в отдельном сообщении ссылкой~~

[Видео](http://i.nexy.one/u/AUOEHl.mp4)

**Comment by CrazyXacker** [comment]
@DonTMover исправления под определенные устройства без наличия данных устройств не производятся
