### ISSUE TITLE
Проблема с уведомлениями 

### ISSUE THREAD

**Issue by Doc010** [AniLabX/AniLabX#24]
Приходят уведомления об уже выпущеных и прочитанных главах манги. 
Версия приложения: 3.12.49(371)
Ссылка на видео:
https://disk.yandex.ru/i/nIDOC3k5LQnqIA
[logcat-2024-04-25-20-20-21-230.txt](https://github.com/AniLabX/AniLabX/files/15113584/logcat-2024-04-25-20-20-21-230.txt)

**Comment by CrazyXacker** [comment]
Не актуально для 5.0
