### ISSUE TITLE
Проблемы с ориентацией

### ISSUE THREAD

**Issue by YURAnix** [AniLabX/AniLabX#26]
Доброе время суток.
Апарат SM-736B/DS
Андрод 14
Версия прграммы 5.0b2 (502)
В главном окне программы не работает переключение ориентации планшетный-книжный. При выходе из встроеного плеера в планшетном режиме главное окно переворачивается и не врзвращается в книжный пока не свернеш окно и не развернеш уже повернутым в книжный режим. Очень неудобно.
И по старой памяти нехватает кнопки обновить сортировку в верху экрана. Приходится каждый раз включать меню сортировки и применять уже выбраную. Или сделайте это автоматически после обновления аниметеки или перехода из других панелей или верните пожалуйста кнопку. Просто удобно было. Можно сделать кнопку отключаемой через меню настроек если на других устройствах она мешает.

**Comment by YURAnix** [comment]
Начала работать смена ориентации. А не может это быть связано с кешем настроек. Странно это... еще понаблюдаю, но пока работает.

**Comment by YURAnix** [comment]
В целом проблема возникает.  Чаще поворот не работает, чем работает. При этом в проигрывателе все работает хорошо. Что-то видимо не так.

**Comment by CrazyXacker** [comment]
Исправлено в новой версии

**Comment by YURAnix** [comment]
5.1b3 (512)
Проблема с ориентацией починилась частично. После выхода из встроеного плеера  в планшетном режиме, так же не работает. Пока не свернешь окно полностью на рабочий стол  и не развернешь.
