### ISSUE TITLE
Кнопка обновления страницы (в х теке) 

### ISSUE THREAD

**Issue by ausypher** [AniLabX/AniLabX#27]
Очень не хватает кнопки обновления страницы в х теках (раньше она была). Если находится в какой то из х-тек и произойдет обновление , чтоб увидеть что и как получило обновление  (не в шторке уведомления) нужно выйти из х теки ,(например зайти в какой-то каталог), затем заново запустить нужную х теку,тогда обновления будут показаны . Раньше достаточно было нажать кнопку обновить (круг как в браузере обновить страницу). Данная кнопка все ещё присутствует в Shikimori теке ,а тут пропала .

**Comment by YURAnix** [comment]
Уточнение. Данная кнопка есть в каталогах. Еще бы в аниметеке была, цены бы небыло. Или проработать события в обход кнопки, чтоб обновления сортировки происходило автоматом после нахождения новых серий или перехода из другого раздела.

**Comment by ausypher** [comment]
> Уточнение. Данная кнопка есть в каталогах. Еще бы в аниметеке была, цены бы небыло. Или проработать события в обход кнопки, чтоб обновления сортировки происходило автоматом после нахождения новых серий или перехода из другого раздела.

Да, я это и имел ввиду. х-теки это манга аниме ранобэ и тд. Просто если фильтр выставлен - допустим по новым главам, кнопка обновить страницу решала проблему-сразу можно было увидеть что новое, а так либо менять фильтрацию несколько раз , либот выходить из х-теки, и потом заново возвращаться

**Comment by CrazyXacker** [comment]
Исправлено в новой версии. Добавлена обработка событий и кнопка
