### ISSUE TITLE
Баг при загрузке манги

### ISSUE THREAD

**Issue by StrannixDeNav** [AniLabX/AniLabX#29]
При массовой загрузке глав в версии 5.0b2(появился с переходом на 5.0, в старых версиях бага нет) при выборе количества глав на загрузку приложение игнорирует эту цифру и загружает все доступные непрочитанные главы. 
Каталог не важен, баг повторяется как в мангатеке так и в ранобетеке.
![Screenrecorder](https://github.com/AniLabX/AniLabX/assets/123468742/5d0de308-dd19-4ac7-9e14-2d22ac43b2c0)

**Comment by CrazyXacker** [comment]
Исправлено в новой версии
