### ISSUE TITLE
Не отображаются (не ищет) обновления аниметеки источника Kodik 

### ISSUE THREAD

**Issue by ausypher** [AniLabX/AniLabX#31]
В версии 5 (на 3й все работает без нареканий) ,есть проблема - не отображает обновления аниметеки , если источник kodik! Не важно какая будет озвучка/сайт ,если kodik то после поиска обновлений ,вручную или автоматически,не отображается огонек о новых сериях. Anilibria , Anistar обновления отображает корректно. Так же замечено ,что при поиске обновлений как бы пропускает kodik , например - 1,2-15 и все , видимо то что под числами от 3 до 14 (для примера,это и есть источник Kodik) просто скипается, поэтому обновления и не отображает!

**Comment by CrazyXacker** [comment]
Исправлено в новой версии
